### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by andcor02** [ARMmbed/mbed-os-example-sockets#1]
So this does not seem to compile anymore, i think some of the include paths have become wrong. Including esp8266-driver/ESP8266Interface.h and EthernetInterface.h?

```
git diff
diff --git a/ESP8266Interface.h b/ESP8266Interface.h
index 7627ac0..bfaa39b 100644
--- a/ESP8266Interface.h
+++ b/ESP8266Interface.h
@@ -17,8 +17,8 @@
 #ifndef ESP8266_INTERFACE_H
 #define ESP8266_INTERFACE_H
 
-#include "network-socket/NetworkStack.h"
-#include "network-socket/WiFiInterface.h"
+#include "netsocket/NetworkStack.h"
+#include "netsocket/WiFiInterface.h"
 #include "ESP8266.h"
```

This removes the first issue. Any idea?

**Comment by geky** [comment]
Sorry for the late response, thanks for reporting this issue!

I think https://github.com/ARMmbed/mbed-os-example-sockets/pull/3 has resolved this. Feel free to reopen this issue if that is not the case.
