### ISSUE TITLE
[OoB_5.11.0-RC2]: Example fails with hard fault on CM3 Fast Model.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/mbed-os-example-sockets#104]
Steps to reproduce:
1. mbed import mbed-os-example-sockets
2. mbed update mbed-os-5.11.0-rc2
3. mbed compile -t GCC_ARM -m FVP_MPS2_M3
4. FVP_MPS2_Cortex-M3 -C fvp_mps2.smsc_91c111.enabled=1 -C fvp_mps2.hostbridge.userNetworking=1 -a BUILD/FVP_MPS2_M3/GCC_ARM/mbed-os-example-sockets.elf
(Optional) 5. (enable telnet on Windows).

Expected:
Sockets example runs and device (FastModel in this case) should obtain an IP address.

Actual:
Fails with OS hard fault.
![hardfault](https://user-images.githubusercontent.com/17567812/49599989-252f8e00-f97a-11e8-87a3-e57cd73cadb7.JPG)

My versions:
```
C:\Ashok\temp\OoB_5_11\mbed-os-example-sockets>mbed ls
mbed-os-example-sockets (#777e4a9d0494, tag: mbed-os-5.11.0-rc2)
`- mbed-os (#d9625811c919, tag: mbed-os-5.11.0-rc2)

C:\Ashok\temp\OoB_5_11\mbed-os-example-sockets>
```
cc @jamesbeyond  @MarceloSalazar

**Comment by jamesbeyond** [comment]
I can reproduce this, I am looking into it

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-4068

**Comment by TacoGrandeTX** [comment]
@jamesbeyond - I added a comment on the internal JIRA

**Comment by jamesbeyond** [comment]
Thanks @TacoGrandeTX,
PR for the fix submitted.

**Comment by ashok-rao** [comment]
Fixed by https://github.com/ARMmbed/mbed-os/pull/8996 .. Closing issue!
