### ISSUE TITLE
Sockets should be bearer independent, add other bearers too

### ISSUE THREAD

**Issue by JanneKiiskila** [ARMmbed/mbed-os-example-sockets#11]
We should really be able to make a simple example even with other bearers. Socket is a socket is a socket. If the bearer complexities make it more difficult, we should consider creating a generic helper layer inbetween to make it easier.

**Comment by JanneKiiskila** [comment]
Should we start using the easy-connect also here?

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3668

**Comment by geky** [comment]
In that case this should mirror the filesystem example:
https://github.com/armmbed/mbed-os-example-filesystem

**Comment by geky** [comment]
@kjbracey-arm, @SeppoTakalo, @SenRamakri  I'm not sure who should be in charge of this repo, but I don't think it can continue to be me.

**Comment by SeppoTakalo** [comment]
This is internal request: IOTPREQ-2566

Closing as we are not tracking new implementations here, they are tracked in Jira.

**Comment by JanneKiiskila** [comment]
Well, done. https://github.com/ARMmbed/mbed-os-example-sockets/pull/78
CI not done, but you can finish off with that. ;) 
- tested with NUCLEO_F401RE and Wifi-X
- REALTEK_RTL8195AM (WiFi)
- K64F (Ethernet)
