### ISSUE TITLE
[Mbed OS OoB 5.14] Cannot see the external IP address

### ISSUE THREAD

**Issue by coisme** [ARMmbed/mbed-os-example-sockets#132]
In the section **Expected Output** in README.md, the line `External IP address` appears and it shows global ip address. 

However, it doesn't appear in the latest example. Here's my log:
```
Mbed OS Socket example
Mbed OS version: 5.14.0

IP address: 10.128.4.30
Netmask: 255.255.255.0
Gateway: 10.128.4.1
sent 56 [GET / HTTP/1.1]
recv 256 [HTTP/1.1 200 OK]
Done
```

The code seems to be removed in this commit
https://github.com/ARMmbed/mbed-os-example-sockets/commit/d421d207b3534aa8f0e7c731b9989ac97ce1cd50#diff-118fcbaaba162ba17933c7893247df3aL86-L88

Please correct the documentation or update the program.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2172

**Comment by adbridge** [comment]
@AnotherButler just FYI

**Comment by michalpasztamobica** [comment]
This is true, thanks for pointing this out @coisme . 
PR on the way: https://github.com/ARMmbed/mbed-os-example-sockets/pull/133
