### ISSUE TITLE
[oob-5.4-rc1] ARCH_PRO runtime fails for all toolchain

### ISSUE THREAD

**Issue by toyowata** [ARMmbed/mbed-os-example-sockets#17]
mbed-CLI 1.0.0
Windows 7
MDK 5.22 (armcc 5.06 b422)
arm-none-eabi-gcc.exe (GNU Tools for ARM Embedded Processors) 4.9.3 20150529
IAR ANSI C/C++ Compiler V7.80.4.12462/W32 for ARM

Compile sucuess for all toolchain, but failed at runtime.

```
Ethernet socket example
IP address is: No IP
sent -3005 [GET / HTTP/1.1]
recv -3005 []
Done
```

**Comment by 0xc0170** [comment]
@geky

**Comment by geky** [comment]
Sorry about the delay, I'm having a hard time reproducing this issue since it seems to work on our network. Currently continuing the issue over here: https://github.com/ARMmbed/mbed-os/issues/4018#issuecomment-289520251

**Comment by toyowata** [comment]
@geky 

I apply the patch locally and this example is now working.

```
Ethernet socket example
IP address is: 10.128.4.33
sent 45 [GET / HTTP/1.1]
recv 64 [HTTP/1.1 301 Moved Permanently]
Done
```

I confirmed that both LPC1768 and ARCH-PRO target worked fine for all toolchain.  Thanks.
