### ISSUE TITLE
Cannot build on DISCO F413

### ISSUE THREAD

**Issue by SonOfFree** [ARMmbed/mbed-os-example-sockets#180]
Compiling soon after download leads to following error. Cannot proceed

`Error: L6218E: Undefined symbol trace_tcp_flags (referred from ../../build/mbed-os/connectivity/nanostack/sal-stack-nanostack/source/Common_Protocols/tcp.DISCO_F413ZH.o).`

**Comment by ciarmcom** [comment]
@SonOfFree This issue has an incomplete or old issue template.For future reference please use an up to date clone of the repository before raising issues. Many thanks.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-3410*

**Comment by paul-szczepanek-arm** [comment]
which branch?

**Comment by paul-szczepanek-arm** [comment]
Can you please make sure you have a clean checkout of mbedos and the example? I compiled it just now without issues.

**Comment by SonOfFree** [comment]
Hi Paul. I am not an experience developer. I am importing the git to the online compiler via the url, update all libraries to latest revision and try to compile. Did it again today and the error is still there. Can it be a problem of the online compiler?

**Comment by SonOfFree** [comment]
Confirmed that it can be compiler on Mbed Studio
