### ISSUE TITLE
Redeclaration of status variable

### ISSUE THREAD

**Issue by DesktopMan** [ARMmbed/mbed-os-example-sockets#185]
The status variable _result_ is redeclared inside the while loop. This seems like an error.

https://github.com/ARMmbed/mbed-os-example-sockets/blob/e76092b773325d0d147211877cb89a4984a7939a/source/main.cpp#L185-L187

**Comment by ciarmcom** [comment]
@DesktopMan This issue has an incomplete or old issue template.For future reference please use an up to date clone of the repository before raising issues. Many thanks.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-3830*

**Comment by paul-szczepanek-arm** [comment]
Thanks for spotting that. I'll make a fix ASAP.

**Comment by paul-szczepanek-arm** [comment]
https://github.com/ARMmbed/mbed-os-example-sockets/pull/186
