### ISSUE TITLE
Ethernet not built with cmake ?

### ISSUE THREAD

**Issue by jeromecoutant** [ARMmbed/mbed-os-example-sockets#197]
### Description of defect

Example is working well with CLI1:
mbed compile -m NUCLEO_F429ZI -t GCC_ARM -f

But not with CLI2:
mbedtools compile -m NUCLEO_F429ZI -t GCC_ARM -f

#### Target(s) affected by this defect ?

NUCLEO_F429ZI with Ethernet

#### Toolchain(s) (name and version) displaying this defect ?

NA

#### What version of Mbed-os are you using (tag or sha) ?

mbed-os-6.15.0

**Comment by 0xc0170** [comment]
What's the error you are getting? How to reproduce?

**Comment by jeromecoutant** [comment]
Mmm need more tests.
Maybe it is "-f" which doesn't work ...?
