### ISSUE TITLE
Results in HTTP/1.1 301 Moved Permanently

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/mbed-os-example-sockets#21]
By default this example makes an HTTP request to developer.mbed.org, which responds that it is actually an HTTPS page (requires TLS security).  So, it always responds with 

sent 45 [GET / HTTP/1.1]
recv 64 [HTTP/1.1 301 Moved Permanently]

Suggest that the URL be changed to some page on HTTP that will reliably respond with a page payload.

**Comment by geky** [comment]
Should be fixed on #22 (using ipify.org as suggested by @bridadan). Let me know if the update is reasonable.

**Comment by geky** [comment]
I think this is resolved, feel free to reopen.
