### ISSUE TITLE
NUCLEO_F746ZG, make_iar: Fails to obtain IP address.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/mbed-os-example-sockets#33]
Steps to reproduce:
1. Clone example repo, switch to OoB branch, update.
2. mbed export -i make_iar -m NUCLEO_F746ZG
3. make clean
4. make

Flash binary to target. Open serial terminal, connect ETH cable to switch and board. Reset target.

Expected: Obtains IP address.
Actual: No IP address obtained. Same procedure passes with make_gcc_arm.
Serial console output below. 1st run is with make_gcc_arm. Success with IP address obtained. 2nd run is with make_iar. Failed as seen below.

```
Ethernet socket example
IP address: 10.2.202.39
Netmask: 255.255.255.0
Gateway: 10.2.202.1
sent 39 [GET / HTTP/1.1]
recv 172 [HTTP/1.1 200 OK]
External IP address: 217.140.96.140
Done
Ethernet socket example
IP address: None
Netmask: None
Gateway: None
sent -3005 [GET / HTTP/1.1]
recv -3005 [GET / HTTP/1.1]
External IP address:
Done
```

Edit: Passes with export to IAR IDE & target obtains an IP address successfully.
Attached makefile from mbed export -i make_iar -m NUCLEO_F746ZG
[Makefile.zip](https://github.com/ARMmbed/mbed-os-example-sockets/files/1060936/Makefile.zip)

C:\Ashok\mbed_CLI\OoB_5_5\Sockets\mbed-os-example-sockets>iccarm --version
IAR ANSI C/C++ Compiler V7.70.2.11706/W32 for ARM

**Comment by ashok-rao** [comment]
@geky .. FYI.

**Comment by 0xc0170** [comment]
cc @LMESTM @jeromecoutant @bcostm @adustm

**Comment by kegilbert** [comment]
I was able to successfully run the socket example with the mbed-os-5.5.0-rc2-oob branch on the example, with mbed-os at mebd-os-5.5.0-rc2 (Commit hash: 162f80099) on a NUCLEO_F746ZG using the make_iar export. EDIT: (RC1 branch worked as well).

```
 Ethernet socket example
 IP address: 192.168.1.141
 Netmask: 255.255.255.0
 Gateway: 192.168.1.1
 sent 39 [GET / HTTP/1.1]
 recv 173 [HTTP/1.1 200 OK]
 External IP address: 217.140.111.135
 Done
```
Generated Makefile from `mbed export -i make_iar -m NUCLEO_F746ZG` and Diffed Makefiles:
[Makefile-Diff.zip](https://github.com/ARMmbed/mbed-os-example-sockets/files/1075886/Makefile-Diff.zip)
IAR version: IAR ANSI C/C++ Compiler V7.80.2.11947/W32 for ARM

**Comment by theotherjimmy** [comment]
@ashok-rao Your makefile looks like it's pre-rtx5. I wonder how that happened...

**Comment by ashok-rao** [comment]
My bad..was using the wrong branch..closing issue now.
