### ISSUE TITLE
[mbed-os-5.6-oob] For FRDM K64F - the output prints could be seen only if PuTTY baud rate is set to 9600, not 115200

### ISSUE THREAD

**Issue by bellashtiv** [ARMmbed/mbed-os-example-sockets#47]
Sounds like a documentation issue. 
When PuTTY baud rate is 115200 I can only see some prints at the very beginning and after that it stuck:
Works perfect for 9600

**Comment by ashok-rao** [comment]
@bellashtiv , can you please provide a link to the docs that mention the baud rate to use?

**Comment by MarceloSalazar** [comment]
This https://github.com/ARMmbed/mbed-os-example-sockets/pull/48 should enough to close this issue.

**Comment by geky** [comment]
I'm going to close this, but it's another drop in the bucket of examples that we need to standardize baud rates.

**Comment by bellashtiv** [comment]
@ashok-rao I didn't find any doc mentioning the baud rate, but usually 115200 works well for K64F.
