### ISSUE TITLE
[OoB_5.8]: export to NUCLEO_F429ZI using make_iar failure

### ISSUE THREAD

**Issue by zvikas** [ARMmbed/mbed-os-example-sockets#68]
C:\work\OOB5.8\mbed-os-example-sockets>mbed export -i make_iar -m NUCLEO_F429ZI
Scan: .
Scan: FEATURE_LWIP

C:\work\OOB5.8\mbed-os-example-sockets>make
"Compile: main.cpp"
process_begin: CreateProcess(NULL, iccarm --no_wrap_diagnostics -e --diag_suppress=Pa050,Pa084,Pa093,Pa082 -On -r -DMBED_DEBUG -DMBED_TRAP_ERRORS_ENABLED=1 --enable_restrict --cpu Cortex-M4F --thumb --dlib_config DLib_Config_Full.h --c++ --no_rtti --no_exceptions --guard_calls --no_static_destruction --guard_calls --no_static_destruction -DTARGET_STM32F429xx -DDEVICE_SPISLAVE=1 -DFEATURE_LWIP=1 -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -D__FPU_PRESENT=1 -DTRANSACTION_QUEUE_SIZE_SPI=2 -DUSBHOST_OTHER -DDEVICE_PORTINOUT=1 -DTARGET_RTOS_M4_M7 -DTARGET_NUCLEO_F429ZI -DDEVICE_LOWPOWERTIMER=1 -DDEVICE_RTC=1 -DTOOLCHAIN_object -DDEVICE_SERIAL_ASYNCH=1 -DTARGET_STM32F4 -D__CMSIS_RTOS -DDEVICE_CAN=1 -DMBED_BUILD_TIMESTAMP=1521119148.91 -DTARGET_CORTEX_M -DTARGET_DEBUG -DDEVICE_I2C_ASYNCH=1 -DTARGET_LIKE_CORTEX_M4 -DDEVICE_ANALOGOUT=1 -DTARGET_M4 -DTARGET_UVISOR_UNSUPPORTED -DDEVICE_PORTOUT=1 -DDEVICE_SPI_ASYNCH=1 -DTOOLCHAIN_IAR -DDEVICE_INTERRUPTIN=1 -DTARGET_CORTEX -DDEVICE_I2C=1 -DTARGET_STM32F429 -D__CORTEX_M4 -DDEVICE_STDIO_MESSAGES=1 -DDEVICE_PWMOUT=1 -DTARGET_FAMILY_STM32 -DTARGET_FF_ARDUINO -DDEVICE_PORTIN=1 -DTARGET_STM -DDEVICE_SERIAL_FC=1 -DDEVICE_TRNG=1 -DTARGET_LIKE_MBED -DTARGET_STM32F429ZI -D__MBED_CMSIS_RTOS_CM -DDEVICE_SLEEP=1 -DDEVICE_SPI=1 -DUSB_STM_HAL -DTARGET_STM32F429xI -DDEVICE_ANALOGIN=1 -DDEVICE_SERIAL=1 -DDEVICE_FLASH=1 -DARM_MATH_CM4 --preinclude=mbed_config.h -I../ -I../. -I.././mbed-os -I.././mbed-os/cmsis -I.././mbed-os/cmsis/TARGET_CORTEX_M -I.././mbed-os/cmsis/TARGET_CORTEX_M/TOOLCHAIN_IAR -I.././mbed-os/drivers -I.././mbed-os/events -I.././mbed-os/events/equeue -I.././mbed-os/features -I.././mbed-os/features/FEATURE_LWIP -I.././mbed-os/features/FEATURE_LWIP/lwip-interface -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip-eth -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F4 -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F429ZI -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip-sys -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip-sys/arch -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/api -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/core -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4 -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6 -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/include -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/priv -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/prot -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/polarssl -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/netif -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/polarssl -I.././mbed-os/features/cellular -I.././mbed-os/features/cellular/easy_cellular -I.././mbed-os/features/cellular/framework -I.././mbed-os/features/cellular/framework/API -I.././mbed-os/features/cellular/framework/AT -I.././mbed-os/features/cellular/framework/common -I.././mbed-os/features/cellular/framework/targets -I.././mbed-os/features/cellular/framework/targets/QUECTEL -I.././mbed-os/features/cellular/framework/targets/QUECTEL/BC95 -I.././mbed-os/features/cellular/framework/targets/QUECTEL/BG96 -I.././mbed-os/features/cellular/framework/targets/TELIT -I.././mbed-os/features/cellular/framework/targets/TELIT/HE910 -I.././mbed-os/features/cellular/framework/targets/UBLOX -I.././mbed-os/features/cellular/framework/targets/UBLOX/LISA_U -I.././mbed-os/features/filesystem -I.././mbed-os/features/filesystem/bd -I.././mbed-os/features/filesystem/fat -I.././mbed-os/features/filesystem/fat/ChaN -I.././mbed-os/features/filesystem/littlefs -I.././mbed-os/features/filesystem/littlefs/littlefs -I.././mbed-os/features/frameworks -I.././mbed-os/features/frameworks/greentea-client -I.././mbed-os/features/frameworks/greentea-client/greentea-client -I.././mbed-os/features/frameworks/greentea-client/source -I.././mbed-os/features/frameworks/unity -I.././mbed-os/features/frameworks/unity/source -I.././mbed-os/features/frameworks/unity/unity -I.././mbed-os/features/frameworks/utest -I.././mbed-os/features/frameworks/utest/source -I.././mbed-os/features/frameworks/utest/utest -I.././mbed-os/features/lorawan -I.././mbed-os/features/lorawan/lorastack -I.././mbed-os/features/lorawan/lorastack/mac -I.././mbed-os/features/lorawan/lorastack/phy -I.././mbed-os/features/lorawan/system -I.././mbed-os/features/mbedtls -I.././mbed-os/features/mbedtls/importer -I.././mbed-os/features/mbedtls/inc -I.././mbed-os/features/mbedtls/inc/mbedtls -I.././mbed-os/features/mbedtls/platform -I.././mbed-os/features/mbedtls/platform/inc -I.././mbed-os/features/mbedtls/platform/src -I.././mbed-os/features/mbedtls/src -I.././mbed-os/features/mbedtls/targets -I.././mbed-os/features/mbedtls/targets/TARGET_STM -I.././mbed-os/features/mbedtls/targets/TARGET_STM/TARGET_STM32F4 -I.././mbed-os/features/nanostack -I.././mbed-os/features/netsocket -I.././mbed-os/features/netsocket/cellular -I.././mbed-os/features/netsocket/cellular/generic_modem_driver -I.././mbed-os/features/netsocket/cellular/utils -I.././mbed-os/features/nvstore -I.././mbed-os/features/nvstore/source -I.././mbed-os/features/storage -I.././mbed-os/hal -I.././mbed-os/hal/storage_abstraction -I.././mbed-os/platform -I.././mbed-os/rtos -I.././mbed-os/rtos/TARGET_CORTEX -I.././mbed-os/rtos/TARGET_CORTEX/TARGET_CORTEX_M -I.././mbed-os/rtos/TARGET_CORTEX/TARGET_CORTEX_M/TOOLCHAIN_IAR -I.././mbed-os/rtos/TARGET_CORTEX/rtx4 -I.././mbed-os/rtos/TARGET_CORTEX/rtx5 -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/Include -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Config -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Include -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_IAR -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_IAR/TARGET_RTOS_M4_M7 -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/Source -I.././mbed-os/targets -I.././mbed-os/targets/TARGET_STM -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F4 -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_IAR -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F4/device -o main.o ../main.cpp, ...) failed.
make (e=2): The system cannot find the file specified.
C:/work/OOB5.8/mbed-os-example-sockets/Makefile:809: recipe for target 'main.o' failed
make[1]: *** [main.o] Error 2
Makefile:25: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by theotherjimmy** [comment]
@zvikas You need the path to the compiler, `iccarm.exe`, in your `PATH` environment variable. Please add it and try again

**Comment by zvikas** [comment]
where can I find iccarm?

**Comment by theotherjimmy** [comment]
Try `"C:\Program Files\IAR Systems\Embedded Workbench 7.5\arm\bin"`

**Comment by zvikas** [comment]
I added the iccarm path to the PATH env variable and got the same error when trying to make.

**Comment by theotherjimmy** [comment]
Did you make sure that you could run `iccarm` and get something on the CMD.exe? You may have to open a new terminal after changing the path through the GUI.

**Comment by theotherjimmy** [comment]
This error:
```
make (e=2): The system cannot find the file specified.
```
means that make tried to run a command, but could not find the executable that was specified on the command line.

**Comment by zvikas** [comment]
Thanks for the tip. It works now.
Issues closed. I just wish it was documented

**Comment by theotherjimmy** [comment]
@zvikas It is documented [here](https://os.mbed.com/docs/v5.7/tools/exporting.html)

**Comment by zvikas** [comment]
Yes, not good enough. I was reading this document and couldn't understand that I am missing PATH to iccarm.

**Comment by theotherjimmy** [comment]
@zvikas How could it be improved?

**Comment by theotherjimmy** [comment]
Would something like the following have helped?

------------
An error, such as the errors below, indicates that the compiler is not found in the `PATH` environment variable. If you encounter an error such as these, please see the instructions above about adding the Compiler to your path.
```
make[1]: armcc: Command not found
```
An error indicating that `armcc`, the Arm Compiler 5 C compiler executable, is not in the `PATH` on Linux

```
make (e=2): The system cannot find the file specified.
```
An error indicating that the compiler was not found in the `PATH` on Windows.

**Comment by theotherjimmy** [comment]
If the documentation is insufficient, than this issue is not resolved.

**Comment by zvikas** [comment]
Yes, something like that can be very helpful.
