### ISSUE TITLE
[OoB_5.8]: export to NUCLEO_F429ZI using uvision5 failure

### ISSUE THREAD

**Issue by zvikas** [ARMmbed/mbed-os-example-sockets#69]
1. mbed export -i uvision5 -m NUCLEO_F429ZI
2. open project file in uvision5 - error 
Error: device not found
Device: STM32F429ZI
Vendor: STMicroelectronic

3. After I manually choose different device of "STM32F429ZITx" the linking failed with error
.\BUILD\mbed-os-example-sockets.axf: error: L6050U: The code size of this image (104240 bytes) exceeds the maximum allowed for this version of the linker.

**Comment by ashok-rao** [comment]
@theotherjimmy .. bump!

**Comment by theotherjimmy** [comment]
@zvikas Get a license, and that'll fix your problem.

**Comment by zvikas** [comment]
Thanks, issue solved.
