### ISSUE TITLE
[OoB_5.8]: online IDE cannot fetch socket example repo

### ISSUE THREAD

**Issue by zvikas** [ARMmbed/mbed-os-example-sockets#70]
Using : https://os-partnerbeta.mbed.com/compiler/#nav:/ 
Trying to import mbed-os-example-sockets 
Error: The remote repository does not exist.

**Comment by ashok-rao** [comment]
@theotherjimmy ..bump!!

**Comment by theotherjimmy** [comment]
@ashok-rao This is not a compiler backend failure. tag @thegecko or @immunda

**Comment by zvikas** [comment]
I managed to import the sockets example by specifying https://github.com/ARMmbed/mbed-os-example-sockets URL instead of choosing the sockets example from the list.
Issue closed.
