### ISSUE TITLE
Minor docs issues in Technology|Ethernet section

### ISSUE THREAD

**Issue by GarySwansonARM** [ARMmbed/mbed-os-example-sockets#81]
https://os-doc-builder.test.mbed.com/docs/development/reference/ethernet-technology.html

"Ethernet can use cable length for up to 100 meters" -> "Ethernet will work with cable lengths of up to 100 meters"

"Since introducing the initial standard, IEEE has improved **the** Ethernet" -> remove 'the'

"Today, most Ethernet devices are capable of automatically negotiating connection speed 10/100/1000 with the switch they are connected" -> "Today, most Ethernet devices are capable of automatically negotiating connection speeds of  10/100/1000 Mbit/s with the switch.

"Most commons are 0x0800 for IPv4 and 0x86DD for IPv6." -> "Most common is ..."

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3699

**Comment by AnotherButler** [comment]
Resolved through Handbook PR #578: https://github.com/ARMmbed/Handbook/pull/578

**Comment by SeppoTakalo** [comment]
Fixed in https://github.com/ARMmbed/Handbook/pull/578
